var VaisseauCreation={
	ouvrirSousOnglet:function(e){$("div.sous_onglet").css({display:"none"}),$('div[name="sous_onglet_'+e+'"]').css({display:"block"})},
	calculer:function(){var e=VaisseauCreation,t={fer:parseInt(e.infrastructure.fer),or:parseInt(e.infrastructure.oro),cristal:parseInt(e.infrastructure.cristal),elyrium:parseInt(e.infrastructure.elyrium),fret:parseInt(e.infrastructure.fret),temps:parseInt(e.infrastructure.temps),attaque:0,bouclier:0,coque:0,nb_reacteur:0,hangar:0,drone:0,poussee:0,siege_antaris:!1,systeme_teleportation:!1,hyperespace:!1};return $('input.composant[type="text"]').each(function(){var a=GestionMethode.parseEntier($(this).val()),r=$(this).attr("data-id_composant"),s=e.tab_composant[r].type;a>0&&(console.log(r+" - "+$(this).attr("name")+" => "+a),t.fer+=a*parseInt(e.tab_composant[r].fer),t.or+=a*parseInt(e.tab_composant[r].oro),t.cristal+=a*parseInt(e.tab_composant[r].cristal),t.elyrium+=a*parseInt(e.tab_composant[r].elyrium),t.fret-=a*parseInt(e.tab_composant[r].fret),t.temps+=a*parseInt(e.tab_composant[r].temps),"autre"!=s&&"vitesse"!=s?t[s]+=a*parseInt(e.tab_composant[r].valeur):"vitesse"==s&&(t.nb_reacteur+=a,t.poussee+=a*parseInt(e.tab_composant[r].valeur),parseInt(e.tab_composant[r].hyperespace)&&(t.hyperespace=!0))),console.log("Fret : "+t.fret)}),$('input.composant[type="checkbox"]').each(function(){if($(this).is(":checked")){var a=$(this).attr("data-id_composant");27==a?(t.siege_antaris=!0,t.bouclier*=1.5):28==a&&(t.systeme_teleportation=!0),t.fer+=parseInt(e.tab_composant[a].fer),t.or+=parseInt(e.tab_composant[a].oro),t.cristal+=parseInt(e.tab_composant[a].cristal),t.elyrium+=parseInt(e.tab_composant[a].elyrium),t.fret-=parseInt(e.tab_composant[a].fret),t.temps+=parseInt(e.tab_composant[a].temps)}}),t},
	selectionnerImage:function(e){var t=VaisseauCreation;$('input[name="image"]').val(e),$('img[name="image_modele"]').attr("src",e),t.ouvrirSousOnglet("description"),t.gererMessage()},
	changerImage:function(){var e=VaisseauCreation,t=$('input[name="image"]').val();$('img[name="image_modele"]').attr("src",t),e.gererMessage()},
	selectionnerInfrastructure:function(){var e=VaisseauCreation,t=$("select#id_infrastructure").val();e.infrastructure=e.tab_infrastructure[t],e.gererComposantInfrastructure(),e.previsualiser()},
	gererComposantInfrastructure:function(){var e=VaisseauCreation,t=e.infrastructure.id_infrastructure;$("input.composant").each(function(){var a=$(this).attr("data-id_composant"),r=e.tab_composant[a].infra_min;if($('div.incompatible[data-association="'+a+'"]').remove(),t>=r)$(this).css({display:"inline-block"});else{var s=$("<div>",{"data-association":a,"class":"incompatible rouge",onmouseover:"montre('Ce composant est incompatible avec cette infrastructure.');",onmouseout:"cache();"}).text("Incompatible");$(this).attr("value",0).css({display:"none"}),$(this).after(s)}})},
	previsualiser:function(){for(var e=VaisseauCreation,t=$('input[name="nom"]').val(),a=new Array("fer","or","cristal","elyrium","attaque","bouclier","coque","fret"),r=e.calculer(),s=0;s<a.length;s++){var n=a[s],i=r[n];$('div.previsualiser td[name="'+n+'"]').text(i>=0?GestionMethode.formatNombre(i):"- "+GestionMethode.formatNombre(Math.abs(i)))}$('div.previsualiser td[name="temps"]').text(DecompteMethode.format(r.temps)),$('div.previsualiser td[name="vitesse"]').text(Math.round(r.poussee>0?r.poussee/parseInt(e.infrastructure.poids)*1e4:0)/100+"%"),$('div.previsualiser td[name="maniabilite"]').text(parseInt(e.infrastructure.maniabilite)+"%"),$('div.previsualiser td[name="drone"]').text(parseInt(r.drone)+" drones"),$('div.previsualiser td span[name="nom_modele"]').html(t.length>=5?t:"..."),$('div.previsualiser td span[name="nom_infrastructrure"]').html(e.infrastructure.nom),$('div.previsualiser td span[name="siege_antaris"]').html(r.siege_antaris?'<span class="vert">oui</span>':'<span class="rouge">non</span>'),$('div.previsualiser td span[name="systeme_teleportation"]').html(r.systeme_teleportation?'<span class="vert">oui</span>':'<span class="rouge">non</span>'),$('div.previsualiser td span[name="hyperespace"]').html(r.hyperespace?'<span class="vert">oui</span>':'<span class="rouge">non</span>'),e.gererMessage()},
	gererMessage:function(){var e=VaisseauCreation;$("div#msg_verifier_modele").html("En attente de vérification du modèle ..."),clearTimeout(e.id_setTimeout),e.id_setTimeout=setTimeout(function(){ActionMethode.envoyerFormulaire("form_creation_vaisseau","msg_verifier_modele","page/vaisseau_creer.php?action=verifierModele",!1,function(){},!1)},500)},
	initialiser:function(){var e=VaisseauCreation;VaisseauCreation.infrastructure=null,AjaxMethode.getDonneesJSON("page/requete_json.php",function(t){e.tab_infrastructure=t,AjaxMethode.getDonneesJSON("page/requete_json.php",function(t){e.tab_composant=t,e.selectionnerInfrastructure(),$('div[name="msg_chargement"]').remove(),$("form#form_creation_vaisseau").css({display:"block"})},"obtenir=liste_composant&securite_cle=bsSaYnxZIYH0BOKVNmUA2VW4ojzvNdc0fHh6go-7ApGJvVBcjD1pzAzyqAmggGRLtIK7GGsiexip0ORiv-_9Ag")},"obtenir=liste_infrastructure&securite_cle=bsSaYnxZIYH0BOKVNmUA2VW4ojzvNdc0fHh6go-7ApGJvVBcjD1pzAzyqAmggGRLtIK7GGsiexip0ORiv-_9Ag"),$('input[type="text"], input[type="checkbox"]').each(function(){"undefined"==typeof $(this).attr("onkeyup")?$(this).attr("onkeyup","javascript:VaisseauCreation.previsualiser();"):$(this).attr("onkeyup",$(this).attr("onkeyup")+" VaisseauCreation.previsualiser();"),"undefined"==typeof $(this).attr("onchange")?$(this).attr("onchange","javascript:VaisseauCreation.previsualiser();"):$(this).attr("onchange",$(this).attr("onchange")+" VaisseauCreation.previsualiser();")})}
	};
	VaisseauCreation.infrastructure=null,VaisseauCreation.tab_composant=new Array,VaisseauCreation.tab_infrastructure=new Array,VaisseauCreation.id_setTimeout=null;