{block name="title" prepend}{$LNG.lm_alliance}{/block}
{block name="content"}
<div id="page_contenu">      <h1>{$LNG.ls_alliance_26} [{$ally_tag}]</h1><div id="div_alliance"><div class="categorie">	<h2>{$LNG.ls_alliance_102}</h2>	<div style="text-align : center; margin : 0px auto 10px auto;">		<img src="/media/alliance_logo/5.jpg?1422617617" alt="" style="max-width : 96%;">	</div>	<div style="float : left; width : 47%; margin : 0px 10px 10px 10px;">		<h3>{$LNG.lm_title_6}</h3>		<table>			<tbody><tr>				<td style="text-align : left; font-weight : bold; width : 150px;">{$LNG.al_ally_info_name} :</td>				<td style="text-align : left;">{$ally_name} </td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.al_ally_info_tag} :</td>				<td style="text-align : left;" class="couleur_alliance">[{$ally_tag}]</td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_103} :</td>				<td style="text-align : left;">
								<a onclick="location.href='game.php?page=playerCard&id={$founderid}';">
									{$founder}</a>
							</td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_104} :</td>				<td style="text-align : left;">{$creation_date}</td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_32} :</td>				<td style="text-align : left;"><span class="{if $recrutement == 0}vert{else}rouge{/if}">{if $recrutement == 0}{$LNG.ls_answer_1}{else}{$LNG.ls_answer_2}{/if}</span></td>			</tr>		</tbody></table>	</div>	<div style="float : left; width : 47%; margin : 0px 10px 10px 10px;">		<h3>Statistics</h3>		<table>			<tbody><tr>				<td style="text-align : left; font-weight : bold; width : 150px;">{$LNG.al_ally_info_members}</td>				<td style="text-align : left;"><span class="couleur_theme">{$ally_member_scount}</span> <span style="font-size : 0.8em;">{$LNG.ls_alliance_107}</span></td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_31} :</td>				<td style="text-align : left;"><span class="couleur_theme">1</span> / {$ally_max_members}</td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_90} :</td>				<td style="text-align : left;"><span class="couleur_theme">{$total_points}</span> <span style="font-size : 0.8em;">pts</span></td>			</tr>			<tr>				<td style="text-align : left; font-weight : bold;">{$LNG.ls_alliance_108} :</td>				<td style="text-align : left;"><span class="couleur_theme">{$average}</span> <span style="font-size : 0.8em;">pts</span></td>			</tr>		</tbody></table>	</div>	<div class="espace"></div>	<div style="float : left; width : 96%; margin : -10px 10px 10px 10px;">		<table>			<tbody><tr>				<td style="text-align : left; font-weight : bold; width : 150px;">{$LNG.al_web_text} :</td>				<td style="text-align : left;"><a href="{$ally_web}" title="{$LNG.ls_alliance_105}">{$ally_web}</a></td>			</tr>		</tbody></table>	</div>	<div class="espace"></div></div>
							
							
							<div class="categorie">	<h2>{$LNG.ls_alliance_106}</h2>	<div class="sous_partie" style="padding-right : 10px;">{if !empty($ally_description)}{$ally_description}{else}{$LNG.al_description_message}{/if}</div></div></div></div>    
{/block}